version: 2.1
executors:
  node:
    docker:
      - image: 'circleci/node:10'
    shell: /bin/bash
    working_directory: ~/unit

jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json checksum
            # when this file is changed, this key will fail
            - v1-npm-deps-{{ checksum "package-lock.json" }}
            # Find the most recently generated cache used from any branch
            - v1-npm-deps-
      - run:
          name: Install Node.js dependencies with Npm
          command: npm install
      - save_cache:
          paths:
            - ./node_modules
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - persist_to_workspace:
          root: ~/unit
          paths:
            - .

  test:
    executor: node
    steps:
      - attach_workspace:
          at: ~/unit
      - run:
          name: Run Test
          command: npm test
      - run:
          name: Generate Test Coverage Report
          command: npm run test:coverage
          when: always
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./reports

  coverage:
    executor: node
    steps:
      - attach_workspace:
          at: ~/unit
      - run:
          name: Generate Test Coverage Report
          command: npm run test:coverage
          when: always
      - store_test_results:
          path: ./coverage
      - store_artifacts:
          path: ./coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
      - coverage:
          requires:
            - build